In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('C:/Users/user/Desktop/ESC_20_2/ESC_Summer_Team5/data/cleansing_data/개인타자.csv', index_col=0)

In [3]:
data

G_ID   GDAY_DS T_ID VS_T_ID  HEADER_NO TB_SC   P_ID  START_CK  \
0      20160401HHLG0  20160401   HH      LG          0     T  60404         0   
1      20160401HHLG0  20160401   LG      HH          0     B  61102         1   
2      20160401HHLG0  20160401   LG      HH          0     B  61186         1   
3      20160401HHLG0  20160401   LG      HH          0     B  62164         0   
4      20160401HHLG0  20160401   HH      LG          0     T  62700         1   
...              ...       ...  ...     ...        ...   ...    ...       ...   
81097  20200719WOSK0  20200719   SK      WO          0     B  75847         1   
81098  20200719WOSK0  20200719   SK      WO          0     B  76802         1   
81099  20200719WOSK0  20200719   SK      WO          0     B  77463         0   
81100  20200719WOSK0  20200719   WO      SK          0     T  78168         1   
81101  20200719WOSK0  20200719   WO      SK          0     T  79456         1   

       BAT_ORDER_NO  PA  ...  P_AB_CN  P_HIT_CN  GYEAR  NAME  POSITION  \
0                 3   1  ...        0         0   2016   송주호         외   
1                 8   3  ...        0         0   2016   유강남         포   
2                 7   4  ...        1         1   2016   이천웅         외   
3                 9   1  ...        0         0   2016   서상우         내   
4                 9   2  ...        0         0   2016   하주석         내   
...             ...  ..  ...      ...       ...    ...   ...       ...   
81097             3   4  ...        1         0   2020    최정         내   
81098             9   4  ...        1         1   2020   김성현         내   
81099             6   1  ...        0         0   2020   채태인         내   
81100             1   5  ...        1         0   2020   서건창         내   
81101             6   4  ...        0         0   2020   이지영         포   

       AGE_VA     MONEY  GWEEK  STADIUM  HOME  
0        28.0    4000만원      금       잠실     0  
1        24.0    8100만원      금       잠실     1  
2        28.0    2800만원      금       잠실     1  
3        27.0    6000만원      금       잠실     1  
4        22.0    3200만원      금       잠실     0  
...       ...       ...    ...      ...   ...  
81097    33.0  120000만원      일       문학     1  
81098    33.0   21000만원      일       문학     1  
81099    38.0   10000만원      일       문학     1  
81100    31.0   35000만원      일       문학     0  
81101    34.0   30000만원      일       문학     0  

[81102 rows x 39 columns]

In [4]:
data.columns

Index(['G_ID', 'GDAY_DS', 'T_ID', 'VS_T_ID', 'HEADER_NO', 'TB_SC', 'P_ID',
       'START_CK', 'BAT_ORDER_NO', 'PA', 'AB', 'RBI', 'RUN', 'HIT', 'H2', 'H3',
       'HR', 'SB', 'CS', 'SH', 'SF', 'BB', 'IB', 'HP', 'KK', 'GD', 'ERR',
       'LOB', 'P_HRA_RT', 'P_AB_CN', 'P_HIT_CN', 'GYEAR', 'NAME', 'POSITION',
       'AGE_VA', 'MONEY', 'GWEEK', 'STADIUM', 'HOME'],
      dtype='object')

In [5]:
data.columns=['게임키','일자','팀코드','상대팀코드','더블헤더코드','초말','선수코드',
            '선발','타순','타자','타수','타점','득점','안타','2루타','3루타',
            '홈런','도루','도루실패','희타','희비','4구','고4','사구','삼진','병살타','실책',
            '잔루','특점권타율','득점권타수','득점권안타','시즌','선수명','포지션',
            '나이','연봉','요일','구장','홈여부']

In [6]:
ab = data.loc[:,'선수코드':'실책']
ab

선수코드  선발  타순  타자  타수  타점  득점  안타  2루타  3루타  ...  도루  도루실패  희타  희비  4구  \
0      60404   0   3   1   1   0   0   1    0    0  ...   0     0   0   0   0   
1      61102   1   8   3   3   0   0   0    0    0  ...   0     0   0   0   0   
2      61186   1   7   4   4   2   2   3    0    0  ...   0     1   0   0   0   
3      62164   0   9   1   0   0   0   0    0    0  ...   0     0   0   0   1   
4      62700   1   9   2   2   0   1   1    0    0  ...   0     0   0   0   0   
...      ...  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ..   ...  ..  ..  ..   
81097  75847   1   3   4   4   0   0   1    0    0  ...   0     0   0   0   0   
81098  76802   1   9   4   3   1   0   3    0    0  ...   0     0   0   0   1   
81099  77463   0   6   1   0   0   0   0    0    0  ...   0     0   0   0   1   
81100  78168   1   1   5   5   0   0   0    0    0  ...   0     0   0   0   0   
81101  79456   1   6   4   4   0   0   0    0    0  ...   0     0   0   0   0   

       고4  사구  삼진  병살타  실책  
0       0   0   0    0   0  
1       0   0   2    0   0  
2       0   0   1    0   0  
3       0   0   0    0   0  
4       0   0   0    0   1  
...    ..  ..  ..  ...  ..  
81097   0   0   1    0   0  
81098   0   0   0    0   0  
81099   0   0   0    0   0  
81100   0   0   0    1   0  
81101   0   0   0    0   0  

[81102 rows x 21 columns]

In [7]:
del ab['선발']
del ab['타순']

In [8]:
ab1 = ab[0:18684]
ab2 = ab[18684:37197]
ab3 = ab[37197:55421]
ab4 = ab[55421:73042]
ab5 = ab[73042:]

In [9]:
happy = ab1['선수코드'].unique()
tmp = ab1.loc[ab1.선수코드 == happy[0],'타자':'실책'].sum()
tmp = pd.DataFrame(tmp)
tmp2 = tmp

In [10]:
for i in range(len(happy)-1):
    tmp = ab1.loc[ab1.선수코드 == happy[i+1],'타자':'실책'].sum()
    tmp = pd.DataFrame(tmp)
    tmp2 = pd.concat([tmp2,tmp],axis=1)

In [11]:
tmp2 = tmp2.transpose()
tmp2.index = np.arange(len(happy))
happy = pd.DataFrame(happy)
happy.columns = ['선수코드']
tmp2 = pd.concat([happy,tmp2],axis=1)
data1 = tmp2
data1

선수코드   타자   타수  타점  득점   안타  2루타  3루타  홈런  도루  도루실패  희타  희비  4구  고4  사구  \
0    60404   52   47   1   3    5    0    0   0   0     2   2   0   3   0   0   
1    61102  297  263  47  28   70    7    0   8   0     0   4   6  17   0   7   
2    61186  320  276  41  38   81   10    1   6   6     9   6   1  34   0   3   
3    62164  137  111  12  18   28    5    0   4   1     0   0   0  25   1   1   
4    62700  441  405  57  58  113   21    1  10   5     7   8   1  18   1   9   
..     ...  ...  ...  ..  ..  ...  ...  ...  ..  ..   ...  ..  ..  ..  ..  ..   
373  66609    0    0   0   0    0    0    0   0   0     0   0   0   0   0   0   
374  97336    0    0   0   0    0    0    0   0   0     0   0   0   0   0   0   
375  65120    1    1   0   0    0    0    0   0   0     0   0   0   0   0   0   
376  97109    1    1   0   0    1    0    0   0   0     0   0   0   0   0   0   
377  66469    4    3   0   0    1    0    0   0   0     0   0   0   1   0   0   

      삼진  병살타  실책  
0     12    1   0  
1     48    6   5  
2     49    3   2  
3     37    1   0  
4    115    3  19  
..   ...  ...  ..  
373    0    0   0  
374    0    0   0  
375    1    0   0  
376    0    0   0  
377    1    0   0  

[378 rows x 19 columns]

In [12]:
happy = ab2['선수코드'].unique()
tmp = ab2.loc[ab2.선수코드 == happy[0],'타자':'실책'].sum()
tmp = pd.DataFrame(tmp)
tmp2 = tmp

for i in range(len(happy)-1):
    tmp = ab2.loc[ab2.선수코드 == happy[i+1],'타자':'실책'].sum()
    tmp = pd.DataFrame(tmp)
    tmp2 = pd.concat([tmp2,tmp],axis=1)
    
tmp2 = tmp2.transpose()
tmp2.index = np.arange(len(happy))
happy = pd.DataFrame(happy)
happy.columns = ['선수코드']
tmp2 = pd.concat([happy,tmp2],axis=1)
data2 = tmp2
data2

선수코드   타자   타수  타점  득점  안타  2루타  3루타  홈런  도루  도루실패  희타  희비  4구  고4  사구  \
0    61700   93   84   4  17  18    2    1   0   1     1   0   0   8   0   1   
1    62234  330  297  26  60  77   13    4   3   7     5   8   0  21   0   4   
2    62768  212  195  26  29  54   12    2   7   0     0   2   0  10   0   5   
3    64086   72   67   7   5  11    2    1   1   1     0   1   1   2   0   1   
4    66209   52   47   2  17  13    2    0   0   3     2   0   0   4   0   1   
..     ...  ...  ...  ..  ..  ..  ...  ...  ..  ..   ...  ..  ..  ..  ..  ..   
355  67893    4    4   0   0   0    0    0   0   0     0   0   0   0   0   0   
356  66162    1    1   0   1   1    0    0   0   0     0   0   0   0   0   0   
357  60263    0    0   0   0   0    0    0   0   0     0   0   0   0   0   0   
358  63903    1    1   0   0   0    0    0   0   0     0   0   0   0   0   0   
359  77452    0    0   0   0   0    0    0   0   0     0   0   0   0   0   0   

     삼진  병살타  실책  
0    19    1   4  
1    55    2  15  
2    59    3   0  
3    21    2   3  
4    12    0   1  
..   ..  ...  ..  
355   2    0   0  
356   0    0   0  
357   0    0   0  
358   1    0   0  
359   0    0   0  

[360 rows x 19 columns]

In [13]:
happy = ab3['선수코드'].unique()
tmp = ab3.loc[ab3.선수코드 == happy[0],'타자':'실책'].sum()
tmp = pd.DataFrame(tmp)
tmp2 = tmp

for i in range(len(happy)-1):
    tmp = ab3.loc[ab3.선수코드 == happy[i+1],'타자':'실책'].sum()
    tmp = pd.DataFrame(tmp)
    tmp2 = pd.concat([tmp2,tmp],axis=1)
    
tmp2 = tmp2.transpose()
tmp2.index = np.arange(len(happy))
happy = pd.DataFrame(happy)
happy.columns = ['선수코드']
tmp2 = pd.concat([happy,tmp2],axis=1)
data3 = tmp2
data3

선수코드   타자   타수  타점  득점   안타  2루타  3루타  홈런  도루  도루실패  희타  희비  4구  고4  사구  \
0    60805    2    0   0   1    0    0    0   0   0     0   0   0   2   0   0   
1    61353  351  330  54  47   92   22    0   6  17     4   1   4  15   1   1   
2    62700  517  484  52  67  123   20    3   9  14    12   1   0  28   0   4   
3    62797  236  209  13  32   53    9    0   2   1     1   0   1  22   2   4   
4    64300  576  511  84  95  147   27    4  20   8     2   1   5  54   2   5   
..     ...  ...  ...  ..  ..  ...  ...  ...  ..  ..   ...  ..  ..  ..  ..  ..   
326  65056    0    0   0   0    0    0    0   0   0     0   0   0   0   0   0   
327  78248    0    0   0   0    0    0    0   0   0     0   0   0   0   0   0   
328  99563    0    0   0   0    0    0    0   0   0     0   0   0   0   0   0   
329  68906    1    1   0   0    0    0    0   0   0     0   0   0   0   0   0   
330  73153    1    1   0   0    0    0    0   0   0     0   0   0   0   0   0   

      삼진  병살타  실책  
0      0    0   0  
1     96    2   3  
2    130    7  18  
3     32    8   1  
4     81   16  13  
..   ...  ...  ..  
326    0    0   0  
327    0    0   0  
328    0    0   0  
329    1    0   0  
330    1    0   0  

[331 rows x 19 columns]

In [14]:
happy = ab4['선수코드'].unique()
tmp = ab4.loc[ab4.선수코드 == happy[0],'타자':'실책'].sum()
tmp = pd.DataFrame(tmp)
tmp2 = tmp

for i in range(len(happy)-1):
    tmp = ab4.loc[ab4.선수코드 == happy[i+1],'타자':'실책'].sum()
    tmp = pd.DataFrame(tmp)
    tmp2 = pd.concat([tmp2,tmp],axis=1)
    
tmp2 = tmp2.transpose()
tmp2.index = np.arange(len(happy))
happy = pd.DataFrame(happy)
happy.columns = ['선수코드']
tmp2 = pd.concat([happy,tmp2],axis=1)
data4 = tmp2
data4

선수코드   타자   타수  타점  득점   안타  2루타  3루타  홈런  도루  도루실패  희타  희비  4구  고4  사구  \
0    61554  140  125  14  14   32    6    0   2   5     2   2   1   9   0   3   
1    62244  505  441  63  58  123   19    9   4   8     2  10   6  41   1   7   
2    62700   20   19   2   3    5    2    0   0   0     0   1   0   0   0   0   
3    62797  129  119   6  11   20    3    0   1   1     0   1   0   9   0   0   
4    68730  525  476  73  74  135   26    2  18  22     7   1   5  38   5   5   
..     ...  ...  ...  ..  ..  ...  ...  ...  ..  ..   ...  ..  ..  ..  ..  ..   
348  65132    7    5   1   0    1    0    0   0   0     0   0   0   2   0   0   
349  66707    1    1   0   0    0    0    0   0   0     0   0   0   0   0   0   
350  69403    1    1   0   0    0    0    0   0   0     0   0   0   0   0   0   
351  78517    0    0   0   0    0    0    0   0   0     0   0   0   0   0   0   
352  68330    8    6   1   1    1    1    0   0   0     0   0   0   2   0   0   

     삼진  병살타  실책  
0    41    4   2  
1    68    5   8  
2     4    1   2  
3    28    2   0  
4    90    6   2  
..   ..  ...  ..  
348   2    0   0  
349   1    0   0  
350   0    0   0  
351   0    0   0  
352   3    0   0  

[353 rows x 19 columns]

In [15]:
happy = ab5['선수코드'].unique()
tmp = ab5.loc[ab5.선수코드 == happy[0],'타자':'실책'].sum()
tmp = pd.DataFrame(tmp)
tmp2 = tmp

for i in range(len(happy)-1):
    tmp = ab5.loc[ab5.선수코드 == happy[i+1],'타자':'실책'].sum()
    tmp = pd.DataFrame(tmp)
    tmp2 = pd.concat([tmp2,tmp],axis=1)
    
tmp2 = tmp2.transpose()
tmp2.index = np.arange(len(happy))
happy = pd.DataFrame(happy)
happy.columns = ['선수코드']
tmp2 = pd.concat([happy,tmp2],axis=1)
data5 = tmp2
data5

선수코드   타자   타수  타점  득점  안타  2루타  3루타  홈런  도루  도루실패  희타  희비  4구  고4  사구  \
0    61208  184  162  10  20  47    8    0   1   8     3   4   2  16   0   0   
1    61353   88   83   9   1  17    0    2   0   1     1   0   0   4   0   1   
2    62700   84   81   8   8  25    5    0   0   3     0   0   0   3   0   0   
3    62895   90   79  14  13  21    3    0   7   0     0   0   2   8   1   1   
4    63450  103   91   2  10  15    3    0   1   0     1   3   0   8   0   1   
..     ...  ...  ...  ..  ..  ..  ...  ...  ..  ..   ...  ..  ..  ..  ..  ..   
294  50357   11   11   0   0   3    1    0   0   0     0   0   0   0   0   0   
295  62864   19   18   5   3   7    0    1   0   0     0   0   0   1   0   0   
296  62146    0    0   0   0   0    0    0   0   0     0   0   0   0   0   0   
297  75342    0    0   0   0   0    0    0   0   0     0   0   0   0   0   0   
298  50730    8    8   1   0   4    3    0   0   0     0   0   0   0   0   0   

     삼진  병살타  실책  
0    24    4   0  
1    24    2   1  
2    18    1   2  
3    24    4   2  
4    28    3   6  
..   ..  ...  ..  
294   5    0   1  
295   2    0   0  
296   0    0   0  
297   0    0   0  
298   1    0   0  

[299 rows x 19 columns]

In [16]:
data_final = pd.concat([data1,data2],axis=0)
data_final = pd.concat([data_final,data3],axis=0)
data_final = pd.concat([data_final,data4],axis=0)
data_final = pd.concat([data_final,data5],axis=0)

data_final.index = np.arange(1721)

year = np.array(["2016","2017","2018","2019","2020"])
year = np.repeat(year, [378,360,331,353,299],axis=0)
year = pd.DataFrame(year)
year.columns=['GYEAR']
data_final = pd.concat([year,data_final],axis=1)

data_final

GYEAR   선수코드   타자   타수  타점  득점   안타  2루타  3루타  홈런  도루  도루실패  희타  희비  4구  \
0     2016  60404   52   47   1   3    5    0    0   0   0     2   2   0   3   
1     2016  61102  297  263  47  28   70    7    0   8   0     0   4   6  17   
2     2016  61186  320  276  41  38   81   10    1   6   6     9   6   1  34   
3     2016  62164  137  111  12  18   28    5    0   4   1     0   0   0  25   
4     2016  62700  441  405  57  58  113   21    1  10   5     7   8   1  18   
...    ...    ...  ...  ...  ..  ..  ...  ...  ...  ..  ..   ...  ..  ..  ..   
1716  2020  50357   11   11   0   0    3    1    0   0   0     0   0   0   0   
1717  2020  62864   19   18   5   3    7    0    1   0   0     0   0   0   1   
1718  2020  62146    0    0   0   0    0    0    0   0   0     0   0   0   0   
1719  2020  75342    0    0   0   0    0    0    0   0   0     0   0   0   0   
1720  2020  50730    8    8   1   0    4    3    0   0   0     0   0   0   0   

      고4  사구   삼진  병살타  실책  
0      0   0   12    1   0  
1      0   7   48    6   5  
2      0   3   49    3   2  
3      1   1   37    1   0  
4      1   9  115    3  19  
...   ..  ..  ...  ...  ..  
1716   0   0    5    0   1  
1717   0   0    2    0   0  
1718   0   0    0    0   0  
1719   0   0    0    0   0  
1720   0   0    1    0   0  

[1721 rows x 20 columns]

In [17]:
a = data_final[['타수']]
a_=a.values 

b = data_final[['안타']]
b_ = b.values

# 타율 = 안타/타수

In [18]:
# 타율 계산
x_ = b_/a_

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


In [19]:
for i in range(len(b_)):
    if b_[i] == 0:
        x_[i] = 0        

x_

array([[0.10638298],
       [0.2661597 ],
       [0.29347826],
       ...,
       [0.        ],
       [0.        ],
       [0.5       ]])

In [20]:
x = pd.DataFrame(x_)
x.columns=['BA']
x

BA
0     0.106383
1     0.266160
2     0.293478
3     0.252252
4     0.279012
...        ...
1716  0.272727
1717  0.388889
1718  0.000000
1719  0.000000
1720  0.500000

[1721 rows x 1 columns]

# 장타율 = (1루타 * 1 + 2루타 * 2 + 3루타 * 3 + 홈런 * 4) / 타수

In [21]:
c1 = data_final[['2루타']]
c2 = data_final[['3루타']]
c3 = data_final[['홈런']]

c1_ = c1.values
c2_ = c2.values
c3_ = c3.values

# 1루타 계산
c0_ = b_ - (c1_+c2_+c3_)

# 루타수 계산
c4_ = (c0_*1) + (c1_*2) + (c2_*3) + (c3_*4)

In [22]:
# 장타율 계산
x1_ = c4_ / a_
x1_

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([[0.10638298],
       [0.38403042],
       [0.40217391],
       ...,
       [       nan],
       [       nan],
       [0.875     ]])

In [23]:
for i in range(len(x1_)):
    if a_[i]==0:
        x1_[i]=0
        
x1_

array([[0.10638298],
       [0.38403042],
       [0.40217391],
       ...,
       [0.        ],
       [0.        ],
       [0.875     ]])

In [24]:
x1=pd.DataFrame(x1_)
x1.columns = ['SLG']
x1

SLG
0     0.106383
1     0.384030
2     0.402174
3     0.405405
4     0.409877
...        ...
1716  0.363636
1717  0.500000
1718  0.000000
1719  0.000000
1720  0.875000

[1721 rows x 1 columns]

# 절대 장타율 = 장타율 - 타율

In [25]:
# 절대 장타율 계산
x2_ = x1_ - x_
x2 = pd.DataFrame(x2_)
x2.columns=['IsoP']
x2

IsoP
0     0.000000
1     0.117871
2     0.108696
3     0.153153
4     0.130864
...        ...
1716  0.090909
1717  0.111111
1718  0.000000
1719  0.000000
1720  0.375000

[1721 rows x 1 columns]

# RC = 득점기여도

* RC = (A x B) / C
* A = 안타 + 볼넷 + 사구 - 도루실패 - 병살타
* B = 루타수 + 0.52 x (도루 + 희타 + 희생플라이) + 0.26 x (볼넷 + 사구 - 고의4구)
* C = 타수 + 볼넷 + 사구 + 희타 +  희생플라이

In [26]:
d0 = data_final[['4구']]
d0_ = d0.values
d1 = data_final[['고4']]
d1_ = d1.values
d2 = data_final[['사구']]
d2_ = d2.values
d3 = data_final[['도루실패']]
d3_ = d3.values
d4 = data_final[['병살타']]
d4_ = d4.values

In [27]:
A_ = b_ + d0_ + d2_ - d3_ - d4_
A_

array([[  5],
       [ 88],
       [106],
       ...,
       [  0],
       [  0],
       [  4]], dtype=int64)

In [28]:
d5 = data_final[['희타']]
d5_ = d5.values
d6 = data_final[['희비']]
d6_ = d6.values
d7 = data_final[['도루']]
d7_ = d7.values
d8 = data_final[['삼진']]
d8_ = d8.values

In [29]:
B_ = c4_ + 0.52*(d7_+d5_+d6_) + 0.26*(d0_+d2_-d1_)

In [30]:
C_ = a_ + d0_ + d2_ + d5_ + d6_

In [31]:
# RC 계산
x3_ = (A_*B_)/C_
x3_

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([[ 0.65576923],
       [33.31555556],
       [42.194625  ],
       ...,
       [        nan],
       [        nan],
       [ 3.5       ]])

In [32]:
for i in range(len(x3_)):
    if C_[i]==0:
        x3_[i]=0

In [33]:
x3=pd.DataFrame(x3_)
x3.columns=['RC']
x3

RC
0      0.655769
1     33.315556
2     42.194625
3     20.124526
4     53.073016
...         ...
1716   1.090909
1717   3.898947
1718   0.000000
1719   0.000000
1720   3.500000

[1721 rows x 1 columns]

# wOBA = 가중 출루율
* 분자 = w1(볼넷 - 고의사구) + w2(사구) + w3(1루타) + w4(2루타) + w5(3루타) + w6(홈런)
* 분모 = 타수 + 볼넷 - 고의사구 + 희생플라이 + 사구

In [34]:
c5=data_final[['실책']]
c5_=c5.values
a2=data_final[['타자']]
a2_=a2.values
a2_

array([[ 52],
       [297],
       [320],
       ...,
       [  0],
       [  0],
       [  8]], dtype=int64)

In [35]:
y1_ = ( ( 0.747 * (d0_[0:378,] - d1_[0:378,]) ) + (0.774 * d2_[0:378,]) + (0.944 * c0_[0:378,]) + (1.273 * c1_[0:378,]) + (1.569 * c2_[0:378,]) + (1.898 * c3_[0:378,]) ) / (a_[0:378,] + d0_[0:378,] - d1_[0:378,] + d6_[0:378,] + d2_[0:378,])

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [36]:
for i in range(len(y1_)):
    if (a_[i] + d0_[i] - d1_[i] + d6_[i] + d2_[i]) == 0:
        y1_[i] = 0
        
print(y1_)

[[0.13922   ]
 [0.32126962]
 [0.36249363]
 [0.37202206]
 [0.33196991]
 [0.19474359]
 [0.22168293]
 [0.37570225]
 [0.31961792]
 [0.38890799]
 [0.3222549 ]
 [0.41210038]
 [0.27806335]
 [0.34951163]
 [0.46283022]
 [0.26483871]
 [0.39654625]
 [0.37758065]
 [0.39866265]
 [0.29458763]
 [0.38167697]
 [0.36834957]
 [0.37327405]
 [0.28879608]
 [0.36650334]
 [0.17980952]
 [0.3064375 ]
 [0.19642857]
 [0.37305097]
 [0.3350493 ]
 [0.39496429]
 [0.35503226]
 [0.39541538]
 [0.19664444]
 [0.38173346]
 [0.463     ]
 [0.32791417]
 [0.41620072]
 [0.41086076]
 [0.31408989]
 [0.25252174]
 [0.38054198]
 [0.28164948]
 [0.36364522]
 [0.2667807 ]
 [0.42613573]
 [0.37726684]
 [0.33161765]
 [0.27697333]
 [0.45023299]
 [0.26889744]
 [0.36012766]
 [0.39778233]
 [0.26923577]
 [0.26318391]
 [0.35463115]
 [0.31486391]
 [0.30823984]
 [0.36839756]
 [0.36221127]
 [0.41522785]
 [0.34482071]
 [0.40486275]
 [0.35429828]
 [0.37530343]
 [0.42457616]
 [0.36299238]
 [0.36065739]
 [0.31539873]
 [0.24405714]
 [0.2911784 ]
 [0.29

In [37]:
y2_ = ( ( 0.728 * (d0_[378:738,] - d1_[378:738,]) ) + (0.756 * d2_[378:738,]) + (0.927 * c0_[378:738,]) + (1.259 * c1_[378:738,]) + (1.558 * c2_[378:738,]) + (1.901 * c3_[378:738,]) ) / (a_[378:738,] + d0_[378:738,] - d1_[378:738,] + d6_[378:738,] + d2_[378:738,])
y2_

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.26409677],
       [0.30886025],
       [0.34848571],
       [0.20673239],
       [0.31505769],
       [0.37897762],
       [0.22831387],
       [0.44990909],
       [0.29150159],
       [0.4131525 ],
       [0.2899537 ],
       [0.2403913 ],
       [0.36010366],
       [0.39673264],
       [0.40350538],
       [0.38400231],
       [0.36449505],
       [0.37486267],
       [0.36470726],
       [0.31427013],
       [0.32025581],
       [0.43948083],
       [0.43666604],
       [0.31120488],
       [0.12786207],
       [0.15492   ],
       [0.        ],
       [0.26505   ],
       [0.32485354],
       [0.39416873],
       [0.32935873],
       [0.30734862],
       [0.33008115],
       [0.26702222],
       [0.31818679],
       [0.41366951],
       [0.39235714],
       [0.37302941],
       [0.37470721],
       [0.44235266],
       [0.34834447],
       [0.28334444],
       [0.34676816],
       [0.21487931],
       [0.33590728],
       [0.206875  ],
       [0.056     ],
       [0.402

In [38]:
for i in range(len(y2_)):
    if (a_[378 + i] + d0_[378 + i] - d1_[378 + i] + d6_[378 + i] + d2_[378 + i]) == 0:
        y2_[i] = 0
        
print(y2_)

[[0.26409677]
 [0.30886025]
 [0.34848571]
 [0.20673239]
 [0.31505769]
 [0.37897762]
 [0.22831387]
 [0.44990909]
 [0.29150159]
 [0.4131525 ]
 [0.2899537 ]
 [0.2403913 ]
 [0.36010366]
 [0.39673264]
 [0.40350538]
 [0.38400231]
 [0.36449505]
 [0.37486267]
 [0.36470726]
 [0.31427013]
 [0.32025581]
 [0.43948083]
 [0.43666604]
 [0.31120488]
 [0.12786207]
 [0.15492   ]
 [0.        ]
 [0.26505   ]
 [0.32485354]
 [0.39416873]
 [0.32935873]
 [0.30734862]
 [0.33008115]
 [0.26702222]
 [0.31818679]
 [0.41366951]
 [0.39235714]
 [0.37302941]
 [0.37470721]
 [0.44235266]
 [0.34834447]
 [0.28334444]
 [0.34676816]
 [0.21487931]
 [0.33590728]
 [0.206875  ]
 [0.056     ]
 [0.40230962]
 [0.40885844]
 [0.27032827]
 [0.36117083]
 [0.36667742]
 [0.33523273]
 [0.31058571]
 [0.2766257 ]
 [0.42556553]
 [0.31772575]
 [0.35573302]
 [0.        ]
 [0.27555769]
 [0.27852734]
 [0.29034975]
 [0.34693849]
 [0.29009141]
 [0.36076673]
 [0.34431594]
 [0.37895538]
 [0.4555648 ]
 [0.31207857]
 [0.29793567]
 [0.29867117]
 [0.33

In [39]:
y3_ = ( ( 0.726 * (d0_[738:1069,] - d1_[738:1069,]) ) + (0.753 * d2_[738:1069,]) + (0.920 * c0_[738:1069,]) + (1.242 * c1_[738:1069,]) + (1.533 * c2_[738:1069,]) + (1.857 * c3_[738:1069,]) ) / (a_[738:1069,] + d0_[738:1069,] - d1_[738:1069,] + d6_[738:1069,] + d2_[738:1069,])
y3_

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.726     ],
       [0.31020917],
       [0.29692248],
       [0.30369231],
       [0.36063351],
       [0.34234081],
       [0.32194144],
       [0.2862    ],
       [0.0575    ],
       [0.39317899],
       [0.34147595],
       [0.39145   ],
       [0.36383704],
       [0.33581658],
       [0.47824268],
       [0.36970922],
       [0.24590411],
       [0.34642174],
       [0.33865076],
       [0.37338608],
       [0.31040597],
       [0.26670345],
       [0.21102564],
       [0.312608  ],
       [0.31919137],
       [0.31314124],
       [0.32215306],
       [0.29974169],
       [0.31144037],
       [0.41049531],
       [0.38698459],
       [0.37516923],
       [0.38131681],
       [0.25053927],
       [0.36477128],
       [0.41157973],
       [0.35745247],
       [0.34124158],
       [0.40624211],
       [0.37737778],
       [0.51195   ],
       [0.347875  ],
       [0.32077806],
       [0.34298351],
       [0.39713793],
       [0.40660584],
       [0.35110294],
       [0.352

In [40]:
for i in range(len(y3_)):
    if (a_[738 + i] + d0_[738 + i] - d1_[738 + i] + d6_[738 + i] + d2_[738 + i]) == 0:
        y3_[i] = 0
        
print(y3_)

[[0.726     ]
 [0.31020917]
 [0.29692248]
 [0.30369231]
 [0.36063351]
 [0.34234081]
 [0.32194144]
 [0.2862    ]
 [0.0575    ]
 [0.39317899]
 [0.34147595]
 [0.39145   ]
 [0.36383704]
 [0.33581658]
 [0.47824268]
 [0.36970922]
 [0.24590411]
 [0.34642174]
 [0.33865076]
 [0.37338608]
 [0.31040597]
 [0.26670345]
 [0.21102564]
 [0.312608  ]
 [0.31919137]
 [0.31314124]
 [0.32215306]
 [0.29974169]
 [0.31144037]
 [0.41049531]
 [0.38698459]
 [0.37516923]
 [0.38131681]
 [0.25053927]
 [0.36477128]
 [0.41157973]
 [0.35745247]
 [0.34124158]
 [0.40624211]
 [0.37737778]
 [0.51195   ]
 [0.347875  ]
 [0.32077806]
 [0.34298351]
 [0.39713793]
 [0.40660584]
 [0.35110294]
 [0.35200645]
 [0.25988832]
 [0.36954113]
 [0.36514978]
 [0.33799781]
 [0.32775281]
 [0.38661851]
 [0.31358252]
 [0.33967969]
 [0.32449807]
 [0.24578195]
 [0.35470299]
 [0.23432   ]
 [0.38831068]
 [0.36204288]
 [0.2677651 ]
 [0.25082677]
 [0.35401078]
 [0.26160465]
 [0.4236099 ]
 [0.2444717 ]
 [0.35068153]
 [0.33553488]
 [0.39636742]
 [0.24

In [41]:
y4_ = ( ( 0.721 * (d0_[1069:1422,] - d1_[1069:1422,]) ) + (0.752 * d2_[1069:1422,]) + (0.945 * c0_[1069:1422,]) + (1.317 * c1_[1069:1422,]) + (1.653 * c2_[1069:1422,]) + (2.074 * c3_[1069:1422,]) ) / (a_[1069:1422,] + d0_[1069:1422,] - d1_[1069:1422,] + d6_[1069:1422,] + d2_[1069:1422,])
y4_

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.31503623],
       [0.34067814],
       [0.28784211],
       [0.21589063],
       [0.35941811],
       [0.32005178],
       [0.40773323],
       [0.36043434],
       [0.36509283],
       [0.34761002],
       [0.38988636],
       [0.32321262],
       [0.30333747],
       [0.25990594],
       [0.36167487],
       [0.36475839],
       [0.39434328],
       [0.32766601],
       [0.33615888],
       [0.16090698],
       [0.31350386],
       [0.28976027],
       [0.36061044],
       [0.22853659],
       [0.3102133 ],
       [0.31598812],
       [0.26173171],
       [0.40684119],
       [0.39283618],
       [0.4145489 ],
       [0.32074836],
       [0.33080412],
       [0.25644944],
       [0.38077718],
       [0.36005036],
       [0.411125  ],
       [0.37272277],
       [0.28667888],
       [0.33026253],
       [0.34078261],
       [0.31086978],
       [0.35053118],
       [0.3025    ],
       [0.28521786],
       [0.29134409],
       [0.25833597],
       [0.34750691],
       [0.267

In [42]:
for i in range(len(y4_)):
    if (a_[1069 + i] + d0_[1069 + i] - d1_[1069 + i] + d6_[1069 + i] + d2_[1069 + i]) == 0:
        y4_[i] = 0
        
print(y4_)

[[0.31503623]
 [0.34067814]
 [0.28784211]
 [0.21589063]
 [0.35941811]
 [0.32005178]
 [0.40773323]
 [0.36043434]
 [0.36509283]
 [0.34761002]
 [0.38988636]
 [0.32321262]
 [0.30333747]
 [0.25990594]
 [0.36167487]
 [0.36475839]
 [0.39434328]
 [0.32766601]
 [0.33615888]
 [0.16090698]
 [0.31350386]
 [0.28976027]
 [0.36061044]
 [0.22853659]
 [0.3102133 ]
 [0.31598812]
 [0.26173171]
 [0.40684119]
 [0.39283618]
 [0.4145489 ]
 [0.32074836]
 [0.33080412]
 [0.25644944]
 [0.38077718]
 [0.36005036]
 [0.411125  ]
 [0.37272277]
 [0.28667888]
 [0.33026253]
 [0.34078261]
 [0.31086978]
 [0.35053118]
 [0.3025    ]
 [0.28521786]
 [0.29134409]
 [0.25833597]
 [0.34750691]
 [0.26756522]
 [0.33046797]
 [0.32107009]
 [0.40641348]
 [0.36576792]
 [0.33656134]
 [0.36415417]
 [0.34389367]
 [0.30623684]
 [0.33460482]
 [0.28376528]
 [0.36338986]
 [0.13773333]
 [0.16714894]
 [0.36769042]
 [0.29041129]
 [0.30801509]
 [0.34936009]
 [0.34820992]
 [0.30618629]
 [0.35079058]
 [0.31465944]
 [0.33856511]
 [0.21104878]
 [0.27

In [43]:
y5_ = ( ( 0.730 * (d0_[1422:,] - d1_[1422:,]) ) + (0.758 * d2_[1422:,]) + (0.935 * c0_[1422:,]) + (1.277 * c1_[1422:,]) + (1.585 * c2_[1422:,]) + (1.942 * c3_[1422:,]) ) / (a_[1422:,] + d0_[1422:,] - d1_[1422:,] + d6_[1422:,] + d2_[1422:,])
y5_

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.32982222],
       [0.23719318],
       [0.32470238],
       [0.3772809 ],
       [0.22656   ],
       [0.22456   ],
       [0.33796154],
       [0.37527863],
       [0.26241791],
       [0.33871255],
       [0.28343636],
       [0.31473118],
       [0.24556643],
       [0.32991928],
       [0.1961129 ],
       [0.284     ],
       [0.41991532],
       [0.26368702],
       [0.13112766],
       [0.34715   ],
       [0.31853714],
       [0.265     ],
       [0.33655823],
       [0.38716129],
       [0.321375  ],
       [0.26263158],
       [0.39634926],
       [0.37505854],
       [0.49674643],
       [0.39990094],
       [0.17091954],
       [0.32891176],
       [0.38778599],
       [0.37380769],
       [0.3597933 ],
       [0.29191628],
       [0.36764854],
       [0.36574074],
       [0.40250545],
       [0.36778261],
       [0.34522222],
       [0.33434979],
       [0.26560377],
       [0.40165031],
       [0.4128664 ],
       [0.13545455],
       [0.31833721],
       [0.281

In [44]:
for i in range(len(y5_)):
    if (a_[1422 + i] + d0_[1422 + i] - d1_[1422 + i] + d6_[1422 + i] + d2_[1422 + i]) == 0:
        y5_[i] = 0
        
print(y5_)

[[0.32982222]
 [0.23719318]
 [0.32470238]
 [0.3772809 ]
 [0.22656   ]
 [0.22456   ]
 [0.33796154]
 [0.37527863]
 [0.26241791]
 [0.33871255]
 [0.28343636]
 [0.31473118]
 [0.24556643]
 [0.32991928]
 [0.1961129 ]
 [0.284     ]
 [0.41991532]
 [0.26368702]
 [0.13112766]
 [0.34715   ]
 [0.31853714]
 [0.265     ]
 [0.33655823]
 [0.38716129]
 [0.321375  ]
 [0.26263158]
 [0.39634926]
 [0.37505854]
 [0.49674643]
 [0.39990094]
 [0.17091954]
 [0.32891176]
 [0.38778599]
 [0.37380769]
 [0.3597933 ]
 [0.29191628]
 [0.36764854]
 [0.36574074]
 [0.40250545]
 [0.36778261]
 [0.34522222]
 [0.33434979]
 [0.26560377]
 [0.40165031]
 [0.4128664 ]
 [0.13545455]
 [0.31833721]
 [0.28160163]
 [0.42659444]
 [0.3187    ]
 [0.34240404]
 [0.36009877]
 [0.35735961]
 [0.3182093 ]
 [0.41700376]
 [0.        ]
 [0.34604545]
 [0.31626596]
 [1.277     ]
 [0.38375243]
 [0.3528141 ]
 [0.35680093]
 [0.        ]
 [0.39307353]
 [0.32575342]
 [0.3015873 ]
 [0.40003831]
 [0.41404583]
 [0.22520833]
 [0.32528972]
 [0.32920301]
 [0.34

In [45]:
# 년도 별로 각기 다른 wOBA 계산 후 다시 병합
x6_ = np.append(y1_,y2_)
x6_ = np.append(x6_,y3_)
x6_ = np.append(x6_,y4_)
x6_ = np.append(x6_,y5_)
print(x6_.shape)

x6 = pd.DataFrame(x6_)
x6.columns = ['wOBA']
x6

(1721,)


wOBA
0     0.139220
1     0.321270
2     0.362494
3     0.372022
4     0.331970
...        ...
1716  0.286091
1717  0.417105
1718  0.000000
1719  0.000000
1720  0.595750

[1721 rows x 1 columns]

# wRC = wOBA기반 득점생산
* [ {(wOBA - 리그 wOBA) / (wOBA scale)} + (리그 득점/리그 타석) ] * 타석

In [46]:
# wRC 계산
z1_ = (((y1_ - 0.362)/1.097) + (0.140 * a2_[0:378,]))
z2_ = (((y2_ - 0.351)/1.107) + (0.135 * a2_[378:738,]))
z3_ = (((y3_ - 0.351)/1.075) + (0.141 * a2_[738:1069,]))
z4_ = (((y4_ - 0.335)/1.242) + (0.118 * a2_[1069:1422,]))
z5_ = (((y5_ - 0.346)/1.14) + (0.134 * a2_[1422:,]))

In [47]:
x4_ = np.append(z1_,z2_)
x4_ = np.append(x4_,z3_)
x4_ = np.append(x4_,z4_)
x4_ = np.append(x4_,z5_)

x4 = pd.DataFrame(x4_)
x4.columns = ['wRC']
x4

wRC
0      7.076919
1     41.542871
2     44.800450
3     19.189136
4     61.712625
...         ...
1716   1.421448
1717   2.608373
1718  -0.303509
1719  -0.303509
1720   1.291079

[1721 rows x 1 columns]

# wRAA = 리그평균 대비 득점생산
* 타석 * (wOBA - 리그 wOBA) / (wOBA scale) 

In [48]:
# wRAA 계산
w1_ = (((y1_ - 0.362)/1.097) * a2_[0:378,])
w2_ = (((y2_ - 0.351)/1.107) * a2_[378:738,])
w3_ = (((y3_ - 0.351)/1.075) * a2_[738:1069,])
w4_ = (((y4_ - 0.335)/1.242) * a2_[1069:1422,])
w5_ = (((y5_ - 0.346)/1.14)  * a2_[1422:,])

x5_ = np.append(w1_,w2_)
x5_ = np.append(x5_,w3_)
x5_ = np.append(x5_,w4_)
x5_ = np.append(x5_,w5_)

x5 = pd.DataFrame(x5_)
x5.columns=['wRAA']
x5

wRAA
0    -10.560219
1    -11.027276
2      0.143994
3      1.251615
4    -12.072261
...         ...
1716  -0.578070
1717   1.185088
1718  -0.000000
1719  -0.000000
1720   1.752632

[1721 rows x 1 columns]

# wRC+
* [ {(wRAA / 타석) / (리그 득점/리그 타석)} + 1] * 100

In [49]:
# wRC+ 계산
p1_ = w1_/(0.140 * a2_[0:378,])
p2_ = w2_/(0.135 * a2_[378:738,])
p3_ = w3_/(0.141 * a2_[738:1069,])
p4_ = w4_/(0.118 * a2_[1069:1422,])
p5_ = w5_/(0.134 * a2_[1422:,])

C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.
C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """
C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  


In [50]:
for i in range(len(p1_)):
    if a2_[i] == 0:
        p1_[i] = 0
        
print(p1_)        

[[-1.45057950e+00]
 [-2.65206247e-01]
 [ 3.21415922e-03]
 [ 6.52562757e-02]
 [-1.95533875e-01]
 [-1.08905072e+00]
 [-9.13641576e-01]
 [ 8.92189555e-02]
 [-2.75960903e-01]
 [ 1.75205014e-01]
 [-2.58790845e-01]
 [ 3.26216817e-01]
 [-5.46533739e-01]
 [-8.13150937e-02]
 [ 6.56532218e-01]
 [-6.32642859e-01]
 [ 2.24939757e-01]
 [ 1.01449702e-01]
 [ 2.38720215e-01]
 [-4.38939778e-01]
 [ 1.28121960e-01]
 [ 4.13437310e-02]
 [ 7.34083375e-02]
 [-4.76650095e-01]
 [ 2.93224427e-02]
 [-1.18629038e+00]
 [-3.61782133e-01]
 [-1.07807936e+00]
 [ 7.19557942e-02]
 [-1.75483163e-01]
 [ 2.14639183e-01]
 [-4.53688106e-02]
 [ 2.17576407e-01]
 [-1.07667376e+00]
 [ 1.28489751e-01]
 [ 6.57637713e-01]
 [-2.21941844e-01]
 [ 3.52915245e-01]
 [ 3.18145328e-01]
 [-3.11955413e-01]
 [-7.12841912e-01]
 [ 1.20731767e-01]
 [-5.23183458e-01]
 [ 1.07124897e-02]
 [-6.19998035e-01]
 [ 4.17604692e-01]
 [ 9.94064291e-02]
 [-1.97827536e-01]
 [-5.53631115e-01]
 [ 5.74508332e-01]
 [-6.06215419e-01]
 [-1.21913037e-02]
 [ 2.3298819

In [51]:
for i in range(len(p2_)):
    if a2_[i+378] == 0:
        p2_[i] = 0
        
for i in range(len(p3_)):
    if a2_[i+738] == 0:
        p3_[i] = 0
        
for i in range(len(p4_)):
    if a2_[i+1069] == 0:
        p4_[i] = 0
        
for i in range(len(p5_)):
    if a2_[i+1422] == 0:
        p5_[i] = 0

In [52]:
q1_ = (p1_+1)*100
q2_ = (p2_+1)*100
q3_ = (p3_+1)*100
q4_ = (p4_+1)*100
q5_ = (p5_+1)*100

In [53]:
x7_ = np.append(q1_,q2_)
x7_ = np.append(x7_,q3_)
x7_ = np.append(x7_,q4_)
x7_ = np.append(x7_,q5_)

x7 = pd.DataFrame(x7_)
x7.columns=['wRC+']
x7

wRC+
0     -45.057950
1      73.479375
2     100.321416
3     106.525628
4      80.446612
...          ...
1716   60.782213
1717  146.547043
1718  100.000000
1719  100.000000
1720  263.491752

[1721 rows x 1 columns]

In [54]:
data_final.columns=['GYEAR','P_ID','PA', 'AB', 'RBI', 'RUN', 'HIT', 'H2', 'H3',
       'HR', 'SB', 'CS', 'SH', 'SF', 'BB', 'IB', 'HP', 'KK', 'GD', 'ERR']
data_final

GYEAR   P_ID   PA   AB  RBI  RUN  HIT  H2  H3  HR  SB  CS  SH  SF  BB  \
0     2016  60404   52   47    1    3    5   0   0   0   0   2   2   0   3   
1     2016  61102  297  263   47   28   70   7   0   8   0   0   4   6  17   
2     2016  61186  320  276   41   38   81  10   1   6   6   9   6   1  34   
3     2016  62164  137  111   12   18   28   5   0   4   1   0   0   0  25   
4     2016  62700  441  405   57   58  113  21   1  10   5   7   8   1  18   
...    ...    ...  ...  ...  ...  ...  ...  ..  ..  ..  ..  ..  ..  ..  ..   
1716  2020  50357   11   11    0    0    3   1   0   0   0   0   0   0   0   
1717  2020  62864   19   18    5    3    7   0   1   0   0   0   0   0   1   
1718  2020  62146    0    0    0    0    0   0   0   0   0   0   0   0   0   
1719  2020  75342    0    0    0    0    0   0   0   0   0   0   0   0   0   
1720  2020  50730    8    8    1    0    4   3   0   0   0   0   0   0   0   

      IB  HP   KK  GD  ERR  
0      0   0   12   1    0  
1      0   7   48   6    5  
2      0   3   49   3    2  
3      1   1   37   1    0  
4      1   9  115   3   19  
...   ..  ..  ...  ..  ...  
1716   0   0    5   0    1  
1717   0   0    2   0    0  
1718   0   0    0   0    0  
1719   0   0    0   0    0  
1720   0   0    1   0    0  

[1721 rows x 20 columns]

In [55]:
data_rate = pd.concat([x,x1],axis=1)
data_rate = pd.concat([data_rate,x2],axis=1)
data_rate = pd.concat([data_rate,x3],axis=1)
data_rate = pd.concat([data_rate,x6],axis=1)
data_rate = pd.concat([data_rate,x5],axis=1)
data_rate = pd.concat([data_rate,x4],axis=1)
data_rate = pd.concat([data_rate,x7],axis=1)

data_final = pd.concat([data_final, data_rate],axis=1)
data_final

GYEAR   P_ID   PA   AB  RBI  RUN  HIT  H2  H3  HR  ...  GD  ERR  \
0     2016  60404   52   47    1    3    5   0   0   0  ...   1    0   
1     2016  61102  297  263   47   28   70   7   0   8  ...   6    5   
2     2016  61186  320  276   41   38   81  10   1   6  ...   3    2   
3     2016  62164  137  111   12   18   28   5   0   4  ...   1    0   
4     2016  62700  441  405   57   58  113  21   1  10  ...   3   19   
...    ...    ...  ...  ...  ...  ...  ...  ..  ..  ..  ...  ..  ...   
1716  2020  50357   11   11    0    0    3   1   0   0  ...   0    1   
1717  2020  62864   19   18    5    3    7   0   1   0  ...   0    0   
1718  2020  62146    0    0    0    0    0   0   0   0  ...   0    0   
1719  2020  75342    0    0    0    0    0   0   0   0  ...   0    0   
1720  2020  50730    8    8    1    0    4   3   0   0  ...   0    0   

            BA       SLG      IsoP         RC      wOBA       wRAA        wRC  \
0     0.106383  0.106383  0.000000   0.655769  0.139220 -10.560219   7.076919   
1     0.266160  0.384030  0.117871  33.315556  0.321270 -11.027276  41.542871   
2     0.293478  0.402174  0.108696  42.194625  0.362494   0.143994  44.800450   
3     0.252252  0.405405  0.153153  20.124526  0.372022   1.251615  19.189136   
4     0.279012  0.409877  0.130864  53.073016  0.331970 -12.072261  61.712625   
...        ...       ...       ...        ...       ...        ...        ...   
1716  0.272727  0.363636  0.090909   1.090909  0.286091  -0.578070   1.421448   
1717  0.388889  0.500000  0.111111   3.898947  0.417105   1.185088   2.608373   
1718  0.000000  0.000000  0.000000   0.000000  0.000000  -0.000000  -0.303509   
1719  0.000000  0.000000  0.000000   0.000000  0.000000  -0.000000  -0.303509   
1720  0.500000  0.875000  0.375000   3.500000  0.595750   1.752632   1.291079   

            wRC+  
0     -45.057950  
1      73.479375  
2     100.321416  
3     106.525628  
4      80.446612  
...          ...  
1716   60.782213  
1717  146.547043  
1718  100.000000  
1719  100.000000  
1720  263.491752  

[1721 rows x 28 columns]

In [56]:
data_final.to_csv('C:/Users/user/Desktop/ESC_20_2/개인타자_시즌별_정헌.csv')